Repository trace4cats/trace4cats, pull requests merged in 2021-02, with the labels that each got.

#262 Update cats-core, cats-laws to 2.4.0
  modules/base-laws/src/test/scala/io/janstenpickle/trace4cats/base/context/laws/BaseSuite.scala
  project/Dependencies.scala
Labels: dependency-update

#256 Update opentelemetry-exporter-jaeger, ... to 0.16.0
  modules/opentelemetry-common/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/common/Trace4CatsSpanData.scala
  project/Dependencies.scala
Labels: dependency-update

#267 Update cats, http4s-backend to 3.1.1
  project/Dependencies.scala
Labels: dependency-update

#268 Update cats-core, cats-laws to 2.4.1
  project/Dependencies.scala
Labels: dependency-update

#272 Update tapir-cats, tapir-http4s-server, ... to 0.17.10
  project/Dependencies.scala
Labels: dependency-update

#271 Update java-jwt to 3.13.0
  project/Dependencies.scala
Labels: dependency-update

#274 Update vulcan, vulcan-enumeratum, ... to 1.4.0
  project/Dependencies.scala
Labels: dependency-update

#275 Add release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#273 Wire span error handler through to inject module
  modules/core/src/main/scala/io/janstenpickle/trace4cats/ErrorHandler.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/HandledError.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/Span.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/package.scala
  modules/core/src/test/scala/io/janstenpickle/trace4cats/SpanSpec.scala
  modules/fs2/src/main/scala/io/janstenpickle/trace4cats/fs2/ContinuationSpan.scala
  modules/fs2/src/main/scala/io/janstenpickle/trace4cats/fs2/syntax/Fs2StreamSyntax.scala
  modules/http4s-server/src/main/scala/io/janstenpickle/trace4cats/http4s/server/Http4sResourceKleislis.scala
  modules/http4s-server/src/main/scala/io/janstenpickle/trace4cats/http4s/server/ServerSyntax.scala
  modules/inject-zio/src/main/scala/io/janstenpickle/trace4cats/inject/zio/SpannedRIOTracer.scala
  modules/inject/src/main/scala/io/janstenpickle/trace4cats/inject/EntryPoint.scala
  modules/inject/src/main/scala/io/janstenpickle/trace4cats/inject/Trace.scala
  modules/inject/src/main/scala/io/janstenpickle/trace4cats/inject/package.scala
  modules/natchez/src/main/scala/io/janstenpickle/trace4cats/natchez/conversions/NatchezToTrace4Cats.scala
  modules/sttp-tapir/src/main/scala/io/janstenpickle/trace4cats/sttp/tapir/ServerEndpointSyntax.scala
  modules/sttp-tapir/src/main/scala/io/janstenpickle/trace4cats/sttp/tapir/TapirResourceKleislis.scala
Labels: enhancement

#277 Update micronaut-core to 2.3.2
  project/Dependencies.scala
Labels: dependency-update

#276 Update zio-interop-cats to 2.3.1.0
  project/Dependencies.scala
Labels: dependency-update

#278 Update http4s-blaze-client, http4s-circe, ... to 0.21.19
  project/Dependencies.scala
Labels: dependency-update

#279 Update fs2-kafka to 1.4.0
  project/Dependencies.scala
Labels: dependency-update

#280 Update sbt-protoc to 1.0.1
  project/plugins.sbt
Labels: dependency-update

#282 Update cats, http4s-backend to 3.1.2
  project/Dependencies.scala
Labels: dependency-update

#283 Update tapir-cats, tapir-http4s-server, ... to 0.17.11
  project/Dependencies.scala
Labels: dependency-update

#285 Update discipline-core to 1.1.4
  project/Dependencies.scala
Labels: dependency-update

#284 Update scalacheck to 1.15.3
  project/Dependencies.scala
Labels: dependency-update

#286 Update scala-collection-compat to 2.4.2
  project/Dependencies.scala
Labels: dependency-update

#287 Update cats-core, cats-laws to 2.4.2
  project/Dependencies.scala
Labels: dependency-update

#288 Update cats-effect, cats-effect-laws to 2.3.2
  project/Dependencies.scala
Labels: dependency-update

#289 Update tapir-cats, tapir-http4s-server, ... to 0.17.12
  project/Dependencies.scala
Labels: dependency-update

#290 Update cats-effect, cats-effect-laws to 2.3.3
  project/Dependencies.scala
Labels: dependency-update

#291 Update fs2-core, fs2-io to 2.5.1
  project/Dependencies.scala
Labels: dependency-update

#293 Update scalatest to 3.2.4
  project/Dependencies.scala
Labels: dependency-update

#292 Update opentelemetry-exporter-jaeger, ... to 0.17.0
  modules/opentelemetry-common/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/common/Trace4CatsSpanData.scala
  project/Dependencies.scala
Labels: dependency-update

#294 Update fs2-core, fs2-io to 2.5.2
  project/Dependencies.scala
Labels: dependency-update

#295 Update discipline-scalatest to 2.1.2
  project/Dependencies.scala
Labels: dependency-update

#296 Update cats, http4s-backend to 3.1.3
  project/Dependencies.scala
Labels: dependency-update

#297 Update cats-testkit-scalatest to 2.1.2
  project/Dependencies.scala
Labels: dependency-update

#298 Update opentelemetry-exporter-jaeger, ... to 0.17.1
  project/Dependencies.scala
Labels: dependency-update

#301 Update fs2-kafka, vulcan, vulcan-enumeratum, ... to 1.4.1
  project/Dependencies.scala
Labels: dependency-update

#300 Update scalatest to 3.2.5
  project/Dependencies.scala
Labels: dependency-update

#302 Update fs2-core, fs2-io to 2.5.3
  project/Dependencies.scala
Labels: dependency-update

#303 Update google-cloud-trace to 1.2.12
  project/Dependencies.scala
Labels: dependency-update

#304 Update micronaut-core to 2.3.3
  project/Dependencies.scala
Labels: dependency-update

#305 Update google-auth-library-credentials to 0.24.0
  project/Dependencies.scala
Labels: dependency-update

#306 Update grpc-api, grpc-okhttp to 1.36.0
  project/Dependencies.scala
Labels: dependency-update

#307 Reduce log noise from queued completer
  modules/exporter-common/src/main/scala/io/janstenpickle/trace4cats/export/QueuedSpanCompleter.scala
Labels: enhancement

#308 Update scala to 2.13.5
  .github/workflows/build.yaml
  modules/agent-common/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/common/AgentTrace.scala
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanExporter.scala
  modules/avro-kafka-consumer/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaConsumer.scala
  modules/avro-kafka-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaSpanCompleter.scala
  modules/avro-kafka-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaSpanExporter.scala
  modules/base-zio/src/test/scala/io/janstenpickle/trace4cats/base/context/zio/laws/GenIOInteropCats.scala
  modules/base-zio/src/test/scala/io/janstenpickle/trace4cats/base/context/zio/laws/catzSpecBase.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/Tracing.scala
  modules/datadog-http-exporter/src/main/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanCompleter.scala
  modules/datadog-http-exporter/src/main/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanExporter.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/Fs2AdvancedExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/Fs2Example.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/Http4sExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/Http4sZioExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/InjectExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/InjectZioExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/NatchezExample.scala
  modules/fs2/src/main/scala/io/janstenpickle/trace4cats/fs2/ContinuationSpan.scala
  modules/fs2/src/main/scala/io/janstenpickle/trace4cats/fs2/syntax/Fs2StreamSyntax.scala
  modules/jaeger-thrift-exporter/src/main/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanExporter.scala
  modules/kafka-client/src/main/scala/io/janstenpickle/trace4cats/kafka/TracedConsumer.scala
  modules/kafka-client/src/main/scala/io/janstenpickle/trace4cats/kafka/syntax/Fs2KafkaSyntax.scala
  modules/meta/src/main/scala/io/janstenpickle/trace4cats/meta/TracedSpanExporter.scala
  modules/newrelic-http-exporter/src/main/scala/io/janstenpickle/trace4cats/newrelic/NewRelicSpanCompleter.scala
  modules/newrelic-http-exporter/src/main/scala/io/janstenpickle/trace4cats/newrelic/NewRelicSpanExporter.scala
  modules/opentelemetry-common/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/common/OpenTelemetryGrpcSpanExporter.scala
  modules/opentelemetry-jaeger-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanCompleter.scala
  modules/opentelemetry-jaeger-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanExporter.scala
  modules/opentelemetry-otlp-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanCompleter.scala
  modules/opentelemetry-otlp-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanExporter.scala
  modules/opentelemetry-otlp-http-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanCompleter.scala
  modules/opentelemetry-otlp-http-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanExporter.scala
  modules/stackdriver-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverGrpcSpanExporter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/strackdriver/StackdriverHttpSpanCompleter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/strackdriver/StackdriverHttpSpanExporter.scala
  modules/tail-sampling-cache-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/cache/LocalCacheSampleDecisionStore.scala
  modules/tail-sampling/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/TailSpanSampler.scala
  project/Dependencies.scala
Labels: dependency-update

#309 Remove redundant type evidence on collector
  modules/collector/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/Collector.scala
Labels: enhancement

#311 Update cats, http4s-backend to 3.1.5
  project/Dependencies.scala
Labels: dependency-update

#312 Update natchez-core to 0.0.20
  project/Dependencies.scala
Labels: dependency-update

#315 Update tapir-cats, tapir-http4s-server, ... to 0.17.13
  project/Dependencies.scala
Labels: dependency-update

#316 Update cats, http4s-backend to 3.1.6
  project/Dependencies.scala
Labels: dependency-update

#317 Update google-auth-library-credentials to 0.24.1
  project/Dependencies.scala
Labels: dependency-update

#318 Update google-cloud-trace to 1.2.13
  project/Dependencies.scala
Labels: dependency-update
