Repository trace4cats/trace4cats, pull requests merged in 2021-05, with the labels that each got.

#462 Update scalacheck to 1.15.4
  project/Dependencies.scala
Labels: dependency-update

#463 Update model:core to 1.4.6
  project/Dependencies.scala
Labels: dependency-update

#465 Update micronaut-core to 2.5.1
  project/Dependencies.scala
Labels: dependency-update

#464 Update kittens to 2.3.0
  project/Dependencies.scala
Labels: dependency-update

#469 Update opentelemetry-exporter-jaeger, ... to 1.2.0
  project/Dependencies.scala
Labels: dependency-update

#471 Port case-insensitive headers to ce3
  build.sbt
  modules/core/src/main/scala/io/janstenpickle/trace4cats/B3SingleToHeaders.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/B3ToHeaders.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/EnvoyToHeaders.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/W3cToHeaders.scala
  modules/core/src/test/scala/io/janstenpickle/trace4cats/B3ToHeadersSpec.scala
  modules/http4s-common/src/main/scala/io/janstenpickle/trace4cats/http4s/common/Http4sHeaders.scala
  modules/http4s-common/src/test/scala/io/janstenpickle/trace4cats/http4s/common/TraceContext.scala
  modules/kafka-client/src/main/scala/io/janstenpickle/trace4cats/kafka/KafkaHeaders.scala
  modules/model/src/main/scala/io/janstenpickle/trace4cats/model/TraceHeaders.scala
  modules/natchez/src/main/scala/io/janstenpickle/trace4cats/natchez/KernelConverter.scala
  modules/sttp-common/src/main/scala/io/janstenpickle/trace4cats/sttp/common/SttpHeaders.scala
  modules/test/src/main/scala/io/janstenpickle/trace4cats/test/ArbitraryInstances.scala
  project/Dependencies.scala
Labels: skip-changelog

#473 Case-insensitive TraceHeaders (review fixes)
  modules/core/src/main/scala/io/janstenpickle/trace4cats/B3SingleToHeaders.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/B3ToHeaders.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/EnvoyToHeaders.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/W3cToHeaders.scala
  modules/model/src/main/scala/io/janstenpickle/trace4cats/model/TraceHeaders.scala
  project/Dependencies.scala
Labels: skip-changelog

#480 Update micronaut-core to 2.5.2
  project/Dependencies.scala
Labels: dependency-update

#481 Update testcontainers-scala-scalatest to 0.39.4
  project/Dependencies.scala
Labels: dependency-update

#482 Update micronaut-core to 2.5.3
  project/Dependencies.scala
Labels: dependency-update

#483 Port attribute helpers to CE3
  .github/workflows/build.yaml
  docs/examples.md
  modules/core/src/main/scala/io/janstenpickle/trace4cats/Span.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/attributes/EnvironmentAttributes.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/attributes/HostAttributes.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/attributes/SystemPropertyAttributes.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/TraceProcessAttributes.scala
  modules/fs2/src/main/scala/io/janstenpickle/trace4cats/fs2/ContinuationSpan.scala
  modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/ClientTracer.scala
  modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/Http4sClientRequest.scala
  modules/http4s-common/src/main/scala/io/janstenpickle/trace4cats/http4s/common/Http4sHeaders.scala
  modules/model/src/main/scala/io/janstenpickle/trace4cats/model/SemanticAttributeKeys.scala
  modules/model/src/main/scala/io/janstenpickle/trace4cats/model/TraceProcessBuilder.scala
  modules/sttp-client3/src/main/scala/io/janstenpickle/trace4cats/sttp/client3/SttpBackendTracer.scala
  modules/sttp-client3/src/main/scala/io/janstenpickle/trace4cats/sttp/client3/SttpRequest.scala
  project/Dependencies.scala
Labels: CE3, skip-changelog

#484 Fix URI attribute helpers
  modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/Http4sClientRequest.scala
  modules/http4s-common/src/main/scala/io/janstenpickle/trace4cats/http4s/common/Http4sHeaders.scala
  modules/sttp-client/src/main/scala/io/janstenpickle/trace4cats/sttp/client/SttpRequest.scala
  modules/sttp-client3/src/main/scala/io/janstenpickle/trace4cats/sttp/client3/SttpRequest.scala
Labels: fix

#485 Add Zipkin exporter
  README.md
  build.sbt
  docker-compose.yaml
  modules/jaeger-integration-test/src/main/scala/io/janstenpickle/trace4cats/test/jaeger/BaseJaegerSpec.scala
  modules/zipkin-http-exporter/src/main/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanCompleter.scala
  modules/zipkin-http-exporter/src/main/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanExporter.scala
  modules/zipkin-http-exporter/src/main/scala/io/janstenpickle/trace4cats/zipkin/ZipkinSpan.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanCompleterSpec.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanExporterSpec.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/package.scala
Labels: enhancement

#486 Add zipkin exporter to collector
  README.md
  build.sbt
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/CommonCollector.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/config/CommonCollectorConfig.scala
Labels: enhancement

#487 Update kind-projector to 0.12.0
  build.sbt
Labels: dependency-update

#490 Update cats-core, cats-laws to 2.6.1
  project/Dependencies.scala
Labels: dependency-update

#491 Update discipline-core to 1.1.5
  project/Dependencies.scala
Labels: dependency-update

#492 Update cats-effect, cats-effect-kernel, ... to 3.1.1
  project/Dependencies.scala
Labels: dependency-update

#493 Update scala-collection-compat to 2.4.4
  project/Dependencies.scala
Labels: dependency-update

#494 Update google-cloud-trace to 1.3.4
  project/Dependencies.scala
Labels: dependency-update

#495 Update grpc-api, grpc-okhttp to 1.37.1
  project/Dependencies.scala
Labels: dependency-update

#499 Update scalatest to 3.2.9
  project/Dependencies.scala
Labels: dependency-update

#498 Update fs2-core, fs2-io to 3.0.3
  project/Dependencies.scala
Labels: dependency-update

#500 Update model:core to 1.4.7
  project/Dependencies.scala
Labels: dependency-update

#502 Update natchez-core to 0.1.3
  project/Dependencies.scala
Labels: dependency-update

#501 Update compilerplugin, scalapb-runtime to 0.11.3
  project/plugins.sbt
Labels: dependency-update

#503 Update discipline-scalatest to 2.1.5
  project/Dependencies.scala
Labels: dependency-update

#504 Update cats, http4s-backend to 3.3.3
  project/Dependencies.scala
Labels: dependency-update

#497 Stop releasing after mergify[bot] PRs
  .github/workflows/build.yaml
Labels: chore

#505 Update kind-projector to 0.13.0
  build.sbt
Labels: dependency-update

#506 Update scala-library to 2.13.6
  project/Dependencies.scala
Labels: dependency-update

#510 Update natchez-core to 0.1.4
  project/Dependencies.scala
Labels: dependency-update

#508 Update case-insensitive to 1.1.4
  project/Dependencies.scala
Labels: dependency-update

#509 Update log4cats-slf4j to 2.1.1
  project/Dependencies.scala
Labels: dependency-update

#511 Update vulcan to 1.7.1
  project/Dependencies.scala
Labels: dependency-update

#512 Update sbt-protoc to 1.0.4
  project/plugins.sbt
Labels: dependency-update

#513 Update grpc-api, grpc-okhttp to 1.38.0
  project/Dependencies.scala
Labels: dependency-update

#516 Update cats, http4s-backend to 3.3.4
  project/Dependencies.scala
Labels: dependency-update

#517 Update tapir-cats, tapir-json-circe to 0.18.0-M11
  project/Dependencies.scala
Labels: dependency-update

#518 Update zio-interop-cats to 3.1.1.0
  project/Dependencies.scala
Labels: dependency-update

#520 Update micronaut-core to 2.5.4
  project/Dependencies.scala
Labels: dependency-update

#521 Update google-auth-library-credentials to 0.26.0
  project/Dependencies.scala
Labels: dependency-update

#522 Update fs2-core, fs2-io to 3.0.4
  project/Dependencies.scala
Labels: dependency-update

#523 Update sbt-tpolecat to 0.1.18
  project/plugins.sbt
Labels: dependency-update

#524 Update kittens to 2.3.2
  project/Dependencies.scala
Labels: dependency-update

#527 Update fs2-kafka to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#528 Fix flaky Jaeger tests
  modules/jaeger-thrift-exporter/src/test/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanCompleterSpec.scala
  modules/jaeger-thrift-exporter/src/test/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanExporterSpec.scala
  modules/jaeger-thrift-exporter/src/test/scala/io/janstenpickle/trace4cats/jaeger/package.scala
  modules/opentelemetry-jaeger-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanCompleterSpec.scala
  modules/opentelemetry-jaeger-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanExporterSpec.scala
  modules/opentelemetry-jaeger-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/package.scala
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanCompleterSpec.scala
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanExporterSpec.scala
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/package.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanCompleterSpec.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanExporterSpec.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/package.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanCompleterSpec.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanExporterSpec.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/package.scala
Labels: fix

#529 Fix flaky Jaeger tests (backport to CE2)
  modules/jaeger-thrift-exporter/src/test/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanCompleterSpec.scala
  modules/jaeger-thrift-exporter/src/test/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanExporterSpec.scala
  modules/jaeger-thrift-exporter/src/test/scala/io/janstenpickle/trace4cats/jaeger/package.scala
  modules/opentelemetry-jaeger-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanCompleterSpec.scala
  modules/opentelemetry-jaeger-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanExporterSpec.scala
  modules/opentelemetry-jaeger-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/package.scala
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanCompleterSpec.scala
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanExporterSpec.scala
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/package.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanCompleterSpec.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanExporterSpec.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/package.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanCompleterSpec.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanExporterSpec.scala
  modules/zipkin-http-exporter/src/test/scala/io/janstenpickle/trace4cats/zipkin/package.scala
Labels: skip-changelog

#525 RateSpanSampler should respect `rootSpansOnly` (backport to CE2)
  modules/rate-sampling/src/main/scala/io/janstenpickle/trace4cats/rate/TokenInterval.scala
  modules/rate-sampling/src/main/scala/io/janstenpickle/trace4cats/rate/sampling/RateSpanSampler.scala
Labels: skip-changelog

#514 Update docs for 0.12.0-RC1
  README.md
  docs/components.md
  docs/examples.md
  docs/sampling.md
Labels: documentation, skip-changelog

#532 Update cats, http4s-backend to 3.3.5
  project/Dependencies.scala
Labels: dependency-update

#535 Update scalacheck-shapeless_1.14 to 1.3.0
  project/Dependencies.scala
Labels: dependency-update

#540 Update sbt-tpolecat to 0.1.19
  project/plugins.sbt
Labels: dependency-update

#539 Update circe-generic-extras, circe-parser to 0.14.1
  project/Dependencies.scala
Labels: dependency-update

#534 Scala 3 preparations: enumeratum and better-monadic-for
  build.sbt
  modules/agent-common/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/common/CommonAgent.scala
  modules/agent-kafka/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/kafka/AgentKafka.scala
  modules/agent/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/Agent.scala
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanCompleter.scala
  modules/avro-kafka-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaSpanCompleter.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/CommonCollector.scala
  modules/datadog-http-exporter/src/main/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanCompleter.scala
  modules/dynamic-sampling-http-server/src/main/scala/io/janstenpickle/trace4cats/sampling/dynamic/http/HttpDynamicSpanSampler.scala
  modules/dynamic-sampling/src/main/scala/io/janstenpickle/trace4cats/sampling/dynamic/HotSwapSpanSampler.scala
  modules/dynamic-sampling/src/main/scala/io/janstenpickle/trace4cats/sampling/dynamic/PollingSpanSampler.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/AdvancedExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/AttributeFiltering.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/TailSampling.scala
  modules/jaeger-thrift-exporter/src/main/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanCompleter.scala
  modules/model/src/main/scala/io/janstenpickle/trace4cats/model/SpanKind.scala
  modules/model/src/main/scala/io/janstenpickle/trace4cats/model/SpanStatus.scala
  modules/newrelic-http-exporter/src/main/scala/io/janstenpickle/trace4cats/newrelic/NewRelicSpanCompleter.scala
  modules/opentelemetry-jaeger-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanCompleter.scala
  modules/opentelemetry-otlp-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanCompleter.scala
  modules/opentelemetry-otlp-http-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanCompleter.scala
  modules/rate-sampling/src/main/scala/io/janstenpickle/trace4cats/rate/DynamicTokenBucket.scala
  modules/rate-sampling/src/test/scala/io/janstenpickle/trace4cats/rate/TokenBucketSpec.scala
  modules/stackdriver-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverGrpcSpanCompleter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverHttpSpanCompleter.scala
  modules/tail-sampling/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/TailSpanSampler.scala
  modules/zipkin-http-exporter/src/main/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanCompleter.scala
  project/Dependencies.scala
Labels: enhancement

#541 Update natchez-core to 0.1.5
  project/Dependencies.scala
Labels: dependency-update

#547 Update http4s to 0.23.0-RC1, http4s-jdk-http-client to 0.5.0-RC1
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/Http4sJdkClient.scala
  modules/datadog-http-exporter/src/main/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanCompleter.scala
  modules/datadog-http-exporter/src/main/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanExporter.scala
  modules/dynamic-sampling-http-server/src/main/scala/io/janstenpickle/trace4cats/sampling/dynamic/http/HttpDynamicSpanSampler.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/Http4sExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/Http4sZioExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/SttpExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/SttpZioExample.scala
  modules/jaeger-integration-test/src/main/scala/io/janstenpickle/trace4cats/test/jaeger/BaseJaegerSpec.scala
  modules/newrelic-http-exporter/src/main/scala/io/janstenpickle/trace4cats/newrelic/NewRelicSpanCompleter.scala
  modules/newrelic-http-exporter/src/main/scala/io/janstenpickle/trace4cats/newrelic/NewRelicSpanExporter.scala
  modules/opentelemetry-otlp-http-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanCompleter.scala
  modules/opentelemetry-otlp-http-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanExporter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverHttpSpanExporter.scala
  modules/zipkin-http-exporter/src/main/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanCompleter.scala
  modules/zipkin-http-exporter/src/main/scala/io/janstenpickle/trace4cats/zipkin/ZipkinHttpSpanExporter.scala
  project/Dependencies.scala
Labels: dependency-update
