Repository trace4cats/trace4cats, pull requests merged in 2021-07, with the labels that each got.

#576 More preparations for Scala 3
  modules/base/src/main/scala/io/janstenpickle/trace4cats/base/context/Lift.scala
  modules/base/src/main/scala/io/janstenpickle/trace4cats/base/context/Local.scala
  modules/base/src/main/scala/io/janstenpickle/trace4cats/base/context/Provide.scala
  modules/base/src/main/scala/io/janstenpickle/trace4cats/base/optics/Getter.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/Span.scala
  modules/core/src/test/scala/io/janstenpickle/trace4cats/B3SingleToHeadersSpec.scala
  modules/core/src/test/scala/io/janstenpickle/trace4cats/B3ToHeadersSpec.scala
  modules/core/src/test/scala/io/janstenpickle/trace4cats/EnvoyToHeadersSpec.scala
  modules/core/src/test/scala/io/janstenpickle/trace4cats/W3cToHeadersSpec.scala
Labels: enhancement

#577 Update fs2-core to 3.0.5
  project/Dependencies.scala
Labels: dependency-update

#578 Update fs2-core to 3.0.6
  project/Dependencies.scala
Labels: dependency-update

#579 Change Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#580 Fix broken links in README
  README.md
Labels: ready-to-merge, skip-changelog, skip-release

#572 Support Cloud Trace headers
  build.sbt
  modules/core/src/main/scala/io/janstenpickle/trace4cats/GoogleCloudTraceToHeaders.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/ToHeaders.scala
  modules/core/src/test/scala/io/janstenpickle/trace4cats/GoogleCloudTraceToHeadersSpec.scala
  modules/fs2/src/main/scala/io/janstenpickle/trace4cats/fs2/syntax/Fs2StreamSyntax.scala
  modules/fs2/src/test/scala/io/janstenpickle/trace4cats/fs2/syntax/Fs2StreamSyntaxSpec.scala
  modules/inject/src/main/scala/io/janstenpickle/trace4cats/inject/EntryPoint.scala
  modules/inject/src/main/scala/io/janstenpickle/trace4cats/inject/Trace.scala
Labels: enhancement

#581 Update sbt-ci-release-early to 2.0.17
  project/plugins.sbt
Labels: dependency-update

#582 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#583 Update scala-collection-compat to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#584 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#586 Fix some documentation urls in the README.
  README.md
Labels: documentation, skip-changelog

#589 Reduce log garbage in tests
  build.sbt
  modules/core/src/test/scala/io/janstenpickle/trace4cats/B3ToHeadersSpec.scala
  project/Dependencies.scala
Labels: ready-to-merge, skip-changelog, skip-release

#590 Backport to 0.11.x: delay GoogleAccountParser#parse properly
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/oauth/GoogleAccountParser.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/oauth/OAuthTokenProvider.scala
Labels: legacy, skip-changelog

#591 Use custom Arbitrary[Instant] instance again
  modules/testkit/src/main/scala/io/janstenpickle/trace4cats/test/ArbitraryInstances.scala
Labels: enhancement

#592 Rework build for series/0.11.x
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/build.yaml
  .github/workflows/ci.yml
  .github/workflows/clean.yml
  .github/workflows/dependency-updates.yml
  .github/workflows/release-drafter.yml
  .mergify.yml
  build.sbt
  ci-release.sbt
  modules/agent-kafka/src/main/docker/build.sh
  modules/agent/src/main/docker/build.sh
  modules/collector-lite/src/main/docker/build.sh
  project/Dependencies.scala
  project/plugins.sbt
Labels: legacy, skip-changelog

#593 Fix condition for docker push
  .github/workflows/ci.yml
  ci-release.sbt
Labels: legacy, skip-changelog, skip-release

#595 Update cats-effect, cats-effect-kernel, ... to 3.2.1
  project/Dependencies.scala
Labels: dependency-update
