Repository trace4cats/trace4cats, pull requests merged in 2021-03, with the labels that each got.

#320 Update opentelemetry-exporter-jaeger, ... to 1.0.0
  modules/opentelemetry-common/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/common/Trace4CatsAttributes.scala
  project/Dependencies.scala
Labels: dependency-update

#319 Update log4cats-slf4j to 1.2.0
  README.md
  docs/components.md
  docs/design.md
  docs/examples.md
  modules/agent-common/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/common/CommonAgent.scala
  modules/agent-kafka/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/kafka/AgentKafka.scala
  modules/agent/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/Agent.scala
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanCompleter.scala
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanExporter.scala
  modules/avro-kafka-consumer/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaConsumer.scala
  modules/avro-kafka-consumer/src/test/scala-2.13/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaConsumerSpec.scala
  modules/avro-kafka-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaSpanCompleter.scala
  modules/avro-server/src/main/scala/io/janstenpickle/trace4cats/avro/server/AvroServer.scala
  modules/avro-test/src/test/scala/io/janstenpickle/trace4cats/avro/test/AvroServerSpec.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/CommonCollector.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/Sampling.scala
  modules/collector-lite/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/CollectorLite.scala
  modules/collector/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/Collector.scala
  modules/datadog-http-exporter/src/main/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanCompleter.scala
  modules/datadog-http-exporter/src/test/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanCompleterSpec.scala
  modules/datadog-http-exporter/src/test/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanExporterSpec.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/AdvancedExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/AllCompleters.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/AttributeFiltering.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/TailSampling.scala
  modules/exporter-common/src/main/scala/io/janstenpickle/trace4cats/export/QueuedSpanCompleter.scala
  modules/exporter-common/src/main/scala/io/janstenpickle/trace4cats/export/QueuedSpanExporter.scala
  modules/jaeger-thrift-exporter/src/main/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanCompleter.scala
  modules/log-exporter/src/main/scala/io/janstenpickle/trace4cats/log/LogSpanCompleter.scala
  modules/log-exporter/src/main/scala/io/janstenpickle/trace4cats/log/LogSpanExporter.scala
  modules/meta/src/test/scala/io/janstenpickle/trace4cats/meta/PipeTracerSpec.scala
  modules/meta/src/test/scala/io/janstenpickle/trace4cats/meta/TracedSpanExporterSpec.scala
  modules/newrelic-http-exporter/src/main/scala/io/janstenpickle/trace4cats/newrelic/NewRelicSpanCompleter.scala
  modules/opentelemetry-jaeger-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanCompleter.scala
  modules/opentelemetry-otlp-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanCompleter.scala
  modules/opentelemetry-otlp-http-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanCompleter.scala
  modules/stackdriver-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverGrpcSpanCompleter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/strackdriver/StackdriverHttpSpanCompleter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/strackdriver/StackdriverHttpSpanExporter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/strackdriver/oauth/GoogleOAuth.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/strackdriver/oauth/InstanceMetadataTokenProvider.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/strackdriver/oauth/OAuthTokenProvider.scala
  modules/tail-sampling-redis-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/redis/RedisSampleDecisionStore.scala
  modules/tail-sampling-redis-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/redis/logAdapters.scala
  modules/tail-sampling-redis-store/src/test/scala/io/janstenpickle/trace4cats/sampling/tail/redis/RedisSampleDecisionStoreSpec.scala
  project/Dependencies.scala
Labels: dependency-update

#323 Update http4s-blaze-client, http4s-circe, ... to 0.21.20
  project/Dependencies.scala
Labels: dependency-update

#322 Update decline-effect to 1.4.0
  project/Dependencies.scala
Labels: dependency-update

#325 Update micronaut-core to 2.3.4
  project/Dependencies.scala
Labels: dependency-update

#327 Update cats, http4s-backend to 3.1.7
  project/Dependencies.scala
Labels: dependency-update

#326 Update java-jwt to 3.14.0
  project/Dependencies.scala
Labels: dependency-update

#328 Update tapir-cats, tapir-http4s-server, ... to 0.17.14
  project/Dependencies.scala
Labels: dependency-update

#330 Update sbt to 1.4.8
  project/build.properties
Labels: dependency-update

#331 Update scalatest to 3.2.6
  project/Dependencies.scala
Labels: dependency-update

#332 Update tapir-cats, tapir-http4s-server, ... to 0.17.15
  project/Dependencies.scala
Labels: dependency-update

#329 Update redis4cats-effects, ... to 0.12.0
  modules/tail-sampling-redis-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/redis/RedisSampleDecisionStore.scala
  modules/tail-sampling-redis-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/redis/logAdapters.scala
  project/Dependencies.scala
Labels: dependency-update

#333 Update micronaut-core to 2.4.0
  project/Dependencies.scala
Labels: dependency-update

#335 Update opentelemetry-exporter-jaeger, ... to 1.0.1
  project/Dependencies.scala
Labels: dependency-update

#336 Update google-cloud-trace to 1.3.0
  project/Dependencies.scala
Labels: dependency-update

#337 Update tapir-cats, tapir-http4s-server, ... to 0.17.16
  project/Dependencies.scala
Labels: dependency-update

#345 Make TokenBucket a resource
  modules/agent-common/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/common/AgentTrace.scala
  modules/agent-common/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/common/CommonAgent.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/CommonCollector.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/Sampling.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/Tracing.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/AdvancedExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/TailSampling.scala
  modules/rate-sampling/src/main/scala/io/janstenpickle/trace4cats/rate/TokenBucket.scala
  modules/rate-sampling/src/main/scala/io/janstenpickle/trace4cats/rate/sampling/RateSpanSampler.scala
  modules/rate-sampling/src/main/scala/io/janstenpickle/trace4cats/rate/sampling/RateTailSpanSampler.scala
  modules/rate-sampling/src/test/scala/io/janstenpickle/trace4cats/rate/TokenBucketSpec.scala
Labels: enhancement

#349 Update testcontainers-scala-scalatest to 0.39.3
  project/Dependencies.scala
Labels: dependency-update

#353 Update sbt-protoc to 1.0.2
  project/plugins.sbt
Labels: dependency-update

#354 Update sbt-native-packager to 1.8.1
  project/plugins.sbt
Labels: dependency-update

#355 Update model:core to 1.3.4
  project/Dependencies.scala
Labels: dependency-update

#356 Update tapir-cats, tapir-http4s-server, ... to 0.17.18
  project/Dependencies.scala
Labels: dependency-update

#358 Update google-auth-library-credentials to 0.25.0
  project/Dependencies.scala
Labels: dependency-update

#357 Update sbt-tpolecat to 0.1.17
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanExporter.scala
  project/plugins.sbt
Labels: dependency-update

#360 Update tapir-cats, tapir-http4s-server, ... to 0.17.19
  project/Dependencies.scala
Labels: dependency-update

#361 Update cats, http4s-backend to 3.1.9
  project/Dependencies.scala
Labels: dependency-update

#351 Easier and safer par operations with Redis sample decision store
  modules/tail-sampling-redis-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/redis/RedisSampleDecisionStore.scala
Labels: enhancement

#362 Update google-auth-library-credentials to 0.25.2
  project/Dependencies.scala
Labels: dependency-update

#363 Update micronaut-core to 2.4.1
  project/Dependencies.scala
Labels: dependency-update

#350 Get rid of InspectableQueue in AvroSpanExporter
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanExporter.scala
  modules/avro-test/src/test/scala/io/janstenpickle/trace4cats/avro/test/AvroServerSpec.scala
Labels: enhancement

#364 Update compilerplugin, scalapb-runtime to 0.11.0
  project/plugins.sbt
Labels: dependency-update

#365 Fix fluky Jaeger tests
  modules/jaeger-thrift-exporter/src/test/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanCompleterSpec.scala
  modules/jaeger-thrift-exporter/src/test/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanExporterSpec.scala
  modules/opentelemetry-jaeger-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanCompleterSpec.scala
  modules/opentelemetry-jaeger-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanExporterSpec.scala
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanCompleterSpec.scala
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanExporterSpec.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanCompleterSpec.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanExporterSpec.scala
Labels: fix

#366 Update cats-effect, cats-effect-laws to 2.4.0
  modules/agent-common/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/common/AgentTrace.scala
  modules/agent-kafka/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/kafka/AgentKafka.scala
  modules/agent/src/main/scala-2.13/io/janstenpickle/trace4cats/agent/Agent.scala
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanCompleter.scala
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanExporter.scala
  modules/avro-kafka-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaSpanCompleter.scala
  modules/avro-kafka-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaSpanExporter.scala
  modules/avro-server/src/main/scala/io/janstenpickle/trace4cats/avro/server/AvroServer.scala
  modules/avro-test/src/test/scala/io/janstenpickle/trace4cats/avro/test/AvroServerSpec.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/CommonCollector.scala
  modules/collector-common/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/common/Sampling.scala
  modules/collector/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/Collector.scala
  modules/core/src/main/scala/io/janstenpickle/trace4cats/Span.scala
  modules/datadog-http-exporter/src/main/scala/io/janstenpickle/trace4cats/datadog/DataDogSpanCompleter.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/AdvancedExample.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/AttributeFiltering.scala
  modules/example/src/main/scala/io/janstenpickle/trace4cats/example/TailSampling.scala
  modules/exporter-common/src/main/scala/io/janstenpickle/trace4cats/export/QueuedSpanCompleter.scala
  modules/exporter-common/src/main/scala/io/janstenpickle/trace4cats/export/QueuedSpanExporter.scala
  modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/ClientTracer.scala
  modules/http4s-server/src/main/scala/io/janstenpickle/trace4cats/http4s/server/Http4sResourceKleislis.scala
  modules/http4s-server/src/test/scala/io/janstenpickle/trace4cats/http4s/server/BaseServerTracerSpec.scala
  modules/jaeger-thrift-exporter/src/main/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanCompleter.scala
  modules/meta/src/test/scala/io/janstenpickle/trace4cats/meta/TracedSpanExporterSpec.scala
  modules/newrelic-http-exporter/src/main/scala/io/janstenpickle/trace4cats/newrelic/NewRelicSpanCompleter.scala
  modules/opentelemetry-jaeger-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanCompleter.scala
  modules/opentelemetry-otlp-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanCompleter.scala
  modules/opentelemetry-otlp-http-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpHttpSpanCompleter.scala
  modules/rate-sampling/src/main/scala/io/janstenpickle/trace4cats/rate/TokenBucket.scala
  modules/stackdriver-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverGrpcSpanCompleter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverHttpSpanCompleter.scala
  modules/sttp-tapir/src/main/scala/io/janstenpickle/trace4cats/sttp/tapir/TapirResourceKleislis.scala
  modules/sttp-tapir/src/test/scala/io/janstenpickle/trace4cats/sttp/tapir/BaseServerEndpointTracerSpec.scala
  modules/tail-sampling-redis-store/src/main/scala/io/janstenpickle/trace4cats/sampling/tail/redis/RedisSampleDecisionStore.scala
  modules/tail-sampling-redis-store/src/test/scala/io/janstenpickle/trace4cats/sampling/tail/redis/RedisSampleDecisionStoreSpec.scala
  project/Dependencies.scala
Labels: dependency-update

#369 Update scalapb-json4s to 0.11.0
  project/Dependencies.scala
Labels: dependency-update

#370 Update log4cats-slf4j to 1.2.1
  project/Dependencies.scala
Labels: dependency-update

#371 Update http4s-jdk-http-client to 0.3.6
  project/Dependencies.scala
Labels: dependency-update

#373 Update grpc-api, grpc-okhttp to 1.36.1
  project/Dependencies.scala
Labels: dependency-update

#372 Update cats, http4s-backend to 3.2.0
  project/Dependencies.scala
Labels: dependency-update

#368 Update model:core to 1.4.0
  project/Dependencies.scala
Labels: dependency-update

#375 Update http4s-blaze-client, ... to 0.21.21
  project/Dependencies.scala
Labels: dependency-update

#379 Update zio-interop-cats to 2.4.0.0
  project/Dependencies.scala
Labels: dependency-update

#378 Update vulcan, vulcan-enumeratum, ... to 1.5.0
  project/Dependencies.scala
Labels: dependency-update

#380 Simplify hostname resolving in UDP Avro exporter
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanExporter.scala
Labels: CE3, enhancement, skip-changelog

#383 Update cats-effect, cats-effect-laws to 2.4.1
  project/Dependencies.scala
Labels: dependency-update

#382 Update cats-core, cats-laws to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#385 Update scala-collection-compat to 2.4.3
  project/Dependencies.scala
Labels: dependency-update

#391 Update fs2-core, fs2-io to 2.5.4
  project/Dependencies.scala
Labels: dependency-update

#392 Update fs2-kafka to 1.4.2
  project/Dependencies.scala
Labels: dependency-update

#393 Update natchez-core to 0.0.21
  project/Dependencies.scala
Labels: dependency-update

#394 Update CE3-related dependencies
  project/Dependencies.scala
Labels: CE3, skip-changelog
