Repository trace4cats/trace4cats, pull requests merged in 2021-04, with the labels that each got.

#396 Update micronaut-core to 2.4.2
  project/Dependencies.scala
Labels: dependency-update

#397 Update natchez-core to 0.0.22
  project/Dependencies.scala
Labels: dependency-update

#398 Update scalatest to 3.2.7
  project/Dependencies.scala
Labels: dependency-update

#399 Proper shifting after async interop in CE2
  modules/collector/src/main/scala-2.13/io/janstenpickle/trace4cats/collector/Collector.scala
  modules/opentelemetry-common/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/common/OpenTelemetryGrpcSpanExporter.scala
  modules/opentelemetry-jaeger-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanCompleter.scala
  modules/opentelemetry-jaeger-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/jaeger/OpenTelemetryJaegerSpanExporter.scala
  modules/opentelemetry-otlp-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanCompleter.scala
  modules/opentelemetry-otlp-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/OpenTelemetryOtlpGrpcSpanExporter.scala
  modules/stackdriver-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverGrpcSpanCompleter.scala
  modules/stackdriver-grpc-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverGrpcSpanExporter.scala
Labels: fix

#400 Update redis4cats-effects, ... to 0.12.1
  project/Dependencies.scala
Labels: dependency-update

#401 Update cats-testkit-scalatest, ... to 2.1.3
  project/Dependencies.scala
Labels: dependency-update

#402 Update redis4cats to 0.13.1
  project/Dependencies.scala
Labels: dependency-update

#403 Update log4cats-slf4j to 1.2.2
  project/Dependencies.scala
Labels: dependency-update

#405 Update cats, http4s-backend to 3.2.3
  project/Dependencies.scala
Labels: dependency-update

#406 Update vulcan, vulcan-enumeratum, ... to 1.5.1
  project/Dependencies.scala
Labels: dependency-update

#407 Update compilerplugin, scalapb-runtime to 0.11.1
  project/plugins.sbt
Labels: dependency-update

#409 Update sbt to 1.5.0
  project/build.properties
Labels: dependency-update

#410 Update java-jwt to 3.15.0
  project/Dependencies.scala
Labels: dependency-update

#412 Upgrade sbt syntax to 1.5.x
  build.sbt
Labels: chore

#415 Update http4s-blaze-client, ... to 0.21.22
  project/Dependencies.scala
Labels: dependency-update

#416 Update opentelemetry-exporter-jaeger, ... to 1.1.0
  project/Dependencies.scala
Labels: dependency-update

#414 Update fs2-kafka to 1.5.0
  modules/avro-kafka-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaSpanExporter.scala
  project/Dependencies.scala
Labels: dependency-update

#417 Update model:core to 1.4.1
  project/Dependencies.scala
Labels: dependency-update

#419 Update grpc-api, grpc-okhttp to 1.37.0
  project/Dependencies.scala
Labels: dependency-update

#420 Update jaeger-thrift to 1.6.0
  project/Dependencies.scala
Labels: dependency-update

#421 Update google-cloud-trace to 1.3.1
  project/Dependencies.scala
Labels: dependency-update

#423 Update google-auth-library-credentials to 0.25.3
  project/Dependencies.scala
Labels: dependency-update

#424 Update sbt-protoc to 1.0.3
  project/plugins.sbt
Labels: dependency-update

#426 Update kittens to 2.2.2
  project/Dependencies.scala
Labels: dependency-update

#427 Update model:core to 1.4.2
  project/Dependencies.scala
Labels: dependency-update

#428 Update model:core to 1.4.3
  project/Dependencies.scala
Labels: dependency-update

#429 Update kafka-clients to 2.8.0
  modules/avro-kafka-consumer/src/test/scala-2.13/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaConsumerSpec.scala
  modules/avro-kafka-exporter/src/test/scala-2.13/io/janstenpickle/trace4cats/avro/kafka/AvroKafkaSpanExporterSpec.scala
  project/Dependencies.scala
Labels: dependency-update

#431 Update google-auth-library-credentials to 0.25.4
  project/Dependencies.scala
Labels: dependency-update

#430 Update cats-core, cats-laws to 2.6.0
  project/Dependencies.scala
Labels: dependency-update

#432 Update cats-effect, cats-effect-laws to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#433 Update scalatest to 3.2.8
  project/Dependencies.scala
Labels: dependency-update

#435 Update google-cloud-trace to 1.3.2
  project/Dependencies.scala
Labels: dependency-update

#436 Update zio-interop-cats to 2.4.1.0
  project/Dependencies.scala
Labels: dependency-update

#438 Update model:core to 1.4.4
  project/Dependencies.scala
Labels: dependency-update

#440 Update jaeger, opentelemetry-collector
  docker-compose.yaml
  modules/opentelemetry-otlp-grpc-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/package.scala
  modules/opentelemetry-otlp-http-exporter/src/test/scala/io/janstenpickle/trace4cats/opentelemetry/otlp/package.scala
Labels: dependency-update

#442 Update natchez-core to 0.0.23
  project/Dependencies.scala
Labels: dependency-update

#441 Update google-auth-library-credentials to 0.25.5
  project/Dependencies.scala
Labels: dependency-update

#444 Update fs2-core, fs2-io to 2.5.5
  project/Dependencies.scala
Labels: dependency-update

#446 Update log4cats-slf4j to 1.3.0
  project/Dependencies.scala
Labels: dependency-update

#447 Update sbt to 1.5.1
  project/build.properties
Labels: dependency-update

#448 Update cats-testkit-scalatest, ... to 2.1.4
  project/Dependencies.scala
Labels: dependency-update

#451 Update micronaut-core to 2.4.3
  project/Dependencies.scala
Labels: dependency-update

#450 Update model:core to 1.4.5
  project/Dependencies.scala
Labels: dependency-update

#452 Update google-cloud-trace to 1.3.3
  project/Dependencies.scala
Labels: dependency-update

#453 Update compilerplugin, scalapb-runtime to 0.11.2
  project/plugins.sbt
Labels: dependency-update

#454 Update vulcan, vulcan-enumeratum, ... to 1.6.0
  project/Dependencies.scala
Labels: dependency-update

#457 Update natchez-core to 0.0.24
  project/Dependencies.scala
Labels: dependency-update

#458 Update micronaut-core to 2.4.4
  project/Dependencies.scala
Labels: dependency-update

#456 Update fs2-kafka to 1.6.1
  project/Dependencies.scala
Labels: dependency-update

#460 Update micronaut-core to 2.5.0
  project/Dependencies.scala
Labels: dependency-update
